### PR TITLE
Update nix support for loongarch

### PR DESCRIPTION
**Pull request by DWwanghao**
Description of changes:
LoongArch is an architecture similar to MIPS. The latest upstream tag of Nix now supports the LoongArch architecture. When I tried to build with nix=0.26.2, I encountered the error:

```c
error[E0432]: unresolved import `self::consts`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.4/src/sys/ioctl/linux.rs:60:15
   |
60 | pub use self::consts::*;
   |               ^^^^^^ could not find `consts` in `self`
```
Upgrading to nix=0.29.0 resolves the issue.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wangnyue** [comment]
Hi, @DWwanghao , thanks for the PR. We are currently not supporting other special architectures. Updating nix only for LoongArch will require extra effort on test perspective. We would recommend to apply the modification and build the rpm package with new nix locally.

**Comment by DWwanghao** [comment]
> Hi, @DWwanghao , thanks for the PR. We are currently not supporting other special architectures. Updating nix only for LoongArch will require extra effort on test perspective. We would recommend to apply the modification and build the rpm package with new nix locally.

**Comment by DWwanghao** [comment]
@wangnyue  Thank you for the feedback, Looking forward to the acceptance in a future upstream version.
I have changed it to a draft
