### ISSUE TITLE
Error when building version 2.4.2 on Ubuntu 26.04

### ISSUE THREAD

**Issue by jsf9k** [aws/efs-utils#349]
I'm getting the following error [when building version 2.4.2 on Ubuntu 26.04](https://github.com/cisagov/ansible-role-amazon-efs-utils/actions/runs/26653646373/job/78558396575?pr=74#step:11:233):
```console
In file included from /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-fips-sys-0.13.9/aws-lc/crypto/fipsmodule/bcm.c:41:
/root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-fips-sys-0.13.9/aws-lc/crypto/fipsmodule/../internal.h: In function 'OPENSSL_memchr':
/root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-fips-sys-0.13.9/aws-lc/crypto/fipsmodule/../internal.h:921:10: error: return discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
921 |   return memchr(s, c, n);
```

Any ideas as to what I can do to get around this failure?

**Comment by jsf9k** [comment]
FWIW, I couldn't get version 3.1.1 to build on Ubuntu 26.04 either:
```console
running: cd \"/tmp/efs-utils/src/proxy/target/release/build/tikv-jemalloc-sys-a79d35e465c22b80/out/build\" && MAKEFLAGS=\" -- RUSTFLAGS=-C\\\\ linker=gcc-13 CXX=g++-13 CC=gcc-13 -j --jobserver-fds=8,9 --jobserver-auth=8,9\" \"make\"
make[1]: Entering directory '/tmp/efs-utils/src/proxy/target/release/build/tikv-jemalloc-sys-a79d35e465c22b80/out/build'
make[1]: Leaving directory '/tmp/efs-utils/src/proxy/target/release/build/tikv-jemalloc-sys-a79d35e465c22b80/out/build'
--- stderr
make[1]: *** No rule to make target '-j'.  Stop.
thread 'main' (8924) panicked at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tikv-jemalloc-sys-0.6.1+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7/build.rs:411:9:
command did not execute successfully: cd \"/tmp/efs-utils/src/proxy/target/release/build/tikv-jemalloc-sys-a79d35e465c22b80/out/build\" && MAKEFLAGS=\" -- RUSTFLAGS=-C\\\\ linker=gcc-13 CXX=g++-13 CC=gcc-13 -j --jobserver-fds=8,9 --jobserver-auth=8,9\" \"make\"
expected success, got: exit status: 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
gmake: *** [Makefile:68: deb] Error 101"], "stdout": "./build-deb.sh\nCleaning deb build workspace\nCreating application directories\nBuilding efs-proxy
```

**Comment by YangjinanHu** [comment]
Hi @jsf9k, support of Ubuntu 26.04 is not currently validated. If you want to build efs-utils on Ubuntu 26.04, there is a [known issue](https://github.com/aws/aws-lc/issues/2010) building aws-lc-fips-sys with GCC 14. It should be fixed in the coming releases after certification completes. You can see "AWS-LC 3 Cryptographic Module" (dynamic and static) still listed on NIST's [Modules In Process](https://csrc.nist.gov/Projects/cryptographic-module-validation-program/modules-in-process/modules-in-process-list) list.

I tested a workaround building with `clang`on RHEL 10 that worked. You can try the same and see if it works on ubuntu 26.04.

On RHEL 10, run the following command before `make rpm`
```
sudo dnf install -y clang 
export CC=clang CXX=clang++
export CFLAGS="-Wno-unused-command-line-argument" CXXFLAGS="-Wno-unused-command-line-argument"
```

**Comment by jsf9k** [comment]
Thank you for the suggestion @YangjinanHu.  Unfortunately switching to `clang` resulted in a different compile error about discarding `const` qualifiers.

Are you planning to add pre-built packages for Ubuntu 26.04 soon?

**Comment by YangjinanHu** [comment]
Thanks for trying that. Supporting Ubuntu 26.04, including pre-built packages, is on our backlog. But I don't have a timeline I can share yet. We'll follow up on this issue here once there's an update.

**Comment by msu-ts** [comment]
Hi there,
Thanks for keeping this issue open and tracked.
We are currently evaluating Ubuntu 26.04 LTS for a production environment and would like to understand whether support for this scenario is on the roadmap.
Is there any update you can share regarding the status of this issue or a rough timeline for when it might be addressed?
Thanks for your help.

**Comment by jsf9k** [comment]
I found that the 24.04 deb files work on 26.04 as well.
